const localData = [
  [
    {
      id: 464052,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Test",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
    {
      id: 464053,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Test 2",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
    {
      id: 464054,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Wonder Woman 1984",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
    {
      id: 464055,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Wonder Woman 1984",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
    {
      id: 464056,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Wonder Woman 1984",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
    {
      id: 464057,
      adult: false,
      backdrop_path: "/images/lupin-avatar.jpg",
      genre_ids: [14, 28, 12],
      original_language: "en",
      original_title: "Wonder Woman 1984",
      overview:
        "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
      popularity: 3460.857,
      poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
      release_date: "2020-12-16",
      title: "Wonder Woman 1984",
      video: false,
      vote_average: 7.1,
      vote_count: 2816,
    },
  ],
];

export default localData;
